// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

declare const process: {
  env: Record<string, string | undefined>;
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7 的数据库连接入口：这里读取 .env 里的 DATABASE_URL。
    // 后续 server/api 通过 Prisma Client 查询 MySQL 时，最终都会使用这个地址。
    url: process.env["DATABASE_URL"],
  },
});
